import pandas as pd

season_end_dates = pd.DataFrame()
accounts = pd.DataFrame()
battle_big = pd.DataFrame()
losing_big = pd.DataFrame()
last_processed = pd.DataFrame()
land = pd.DataFrame()
collection = pd.DataFrame()
rating = pd.DataFrame()
season_dec = pd.DataFrame()
season_merits = pd.DataFrame()
season_sps = pd.DataFrame()
season_unclaimed_sps = pd.DataFrame()
season_vouchers = pd.DataFrame()
season_glint = pd.DataFrame()
season_credits = pd.DataFrame()
season_modern_battle_info = pd.DataFrame()
season_wild_battle_info = pd.DataFrame()
portfolio = pd.DataFrame()
portfolio_investments = pd.DataFrame()
view_portfolio_accounts = pd.DataFrame()
secrets = pd.DataFrame()
