filter_settings = 'global-filter-settings'

filter_user_dropdown = 'dropdown-user-selection'
filter_rule_sets_dropdown = 'dropdown-rule-sets-selection'
filter_season_dropdown = 'dropdown-season-selection'
filter_sort_by_dropdown = 'dropdown-sort-by-selection'
filter_from_date_text = 'filter-from-date'
filter_battle_count = 'filter-battle-count'
filter_group_levels_radio_selection = 'radio-by-selection'
filter_abilities_dropdown = 'filter-abilities-dropdown'
