add_button = 'add-account-btn'
remove_button = 'remove-account-btn'
error_text_account = 'error-text-account'
current_accounts = 'current-accounts'
account_name_input = 'account-name-input'
button_div = 'button-div'