account_added = 'account_added'
account_removed = 'account_removed'
account_updated = 'account-updated'
add_button = 'add-account-btn'
remove_button = 'remove-account-btn'
account_text = 'account-text'
current_accounts = 'current-accounts'
account_name_input = 'account-name-input'

posting_key_user_dropdown = 'config-user-dropdown'
posting_key_input = 'config-posting-key'
posting_key_text = 'config-posting-key-text'
add_posting_key_button = 'config-add-posting-key-button'

update_account_info = 'config-update-account-info'
