account_added = 'account_added'
account_removed = 'account_removed'
add_button = 'add-account-btn'
remove_button = 'remove-account-btn'
account_text = 'account-text'
current_accounts = 'current-accounts'
account_name_input = 'account-name-input'
button_div = 'button-div'
