name: Flake8

on:
  push:
    branches:
      - '*'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install flake8-html
          pip install genbadge[all]

      - name: Run Flake8
        run: |
          flake8 src --exit-zero --format=html --htmldir ./reports/flake8 --statistics --tee --output-file ./reports/flake8/flake8stats.txt
          genbadge flake8 -o ./reports/flake8-badge
